---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip

install:
  # Install Ansible.
  - pip install ansible

script:
  # inst all ansible
  - "ansible-playbook -i ansible/inventory ansible/redeploy.yml --connection=local --sudo"
