---
- name: Deploy new changes
  hosts: all
  become: yes
  tasks:
    - name: chdir to proj_root
      shell: cd ~
    - name: which directory
      shell: pwd
    - name: Initiate terraform
      shell: terraform init terraform
    - name: validate website terraform
      shell: terraform validate terraform/website
    - name: select terraform prod
      shell: terraform workspace select prod
    - name: Apply new terraform to production
      shell: terraform apply -auto-approve website
